// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'customer_repository.dart';
export 'customer_service.dart';
export 'customer_viewmodel.dart';